server:
  port: 8080

spring:
  application:
    name: ccloud-main
  profiles:
    active: dev
  jackson:
    # 常用请求与响应自动转下划线，空值字段不传输
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null