server:
  port: 8080
  tomcat:
    #tomcat的url编码为utf-8，解决中文乱码的问题。
    uri-encoding: utf-8
    #tomcat允许的post最大值为1GB
    max-http-form-post-size: 1073741824
  servlet:
    context-path: /ccloud

swagger:
  print-init: true #非必需,默认true,控制台打印swagger url
  enabled: true #非必需,默认true
  docket:
    base-package: com.ccloud.main.controller   #必需

spring:
  cache:
    redis:
      time-to-live: 10s
      key-prefix: 'c-cloud_'
    type: redis
  application:
    name: ccloud-main
  profiles:
    include: db
  jackson:
    # 常用请求与响应自动转下划线，空值字段不传输
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null



fastdep:
  shiro-jwt:
    filter: #shiro过滤规则
      admin:
        path: /**
        role: jwt # jwt为需要进行token校验
      verifyCode:
        path: /verifyCode
        role: anon # anon为无需校验
      reg:
        path: /reg
        role: anon # anon为无需校验
      login:
        path: /login
        role: anon # anon为无需校验
      swagger:
        path: /swagger-ui.html
        role: anon
      swagger-webjar:
        path: /webjars/**
        role: anon
      swagger-v2:
        path: /v2/**
        role: anon
      swagger-resource:
        path: /swagger-resources/**
        role: anon
      swagger-doc:
        path: /doc.html
        role: anon
    secret: "6Dx8SIuaHXJYnpsK18SSpjPs50lZcT52" # jwt秘钥
    #    expireTime: 7200000 # token有效期
    prefix: "C-Cloud "  # token校验时的前缀
    signPrefix: "C-Cloud " # token生成签名的前缀
    header: "CC-Authorization" # token校验时的header头
    #    以下对应为shiro配置参数，无特殊需求无需配置
#    loginUrl: /login
#    successUrl:
#    unauthorizedUrl:
#    filterChainDefinitions:
#mybatis-plus
mybatis-plus:
  global-config:
    db-config:
      id-type: auto
    banner: false
  mapper-locations: classpath*:com/ccloud/main/mapper/xml/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
