#mysql
spring:
  datasource:
    url: jdbc:mysql://106.13.235.137:3306/ccloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    user-name: root
    password: l83OpIzu6E
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
          minimum-idle: 3
          maximum-pool-size: 10
          max-lifetime: 30000
          connection-test-query: SELECT 1
  redis:
    database: 1
    host: localhost
    port: 6379
    password: '123456'
    timeout: 2000ms #连接超时时间
    lettuce:
      pool:
        max-active: 100 #接池最大连接数（使用负值表示没有限制）
        max-wait: -1ms #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10 #最大空闲连接数，负值无限制
        min-idle: 5 #最小空闲连接数，负值无限制
